# Example workflow for a consumer repository
# This file should be placed in .github/workflows/ in the consuming repository

name: Claude AI Integration

# Concurrency control to prevent multiple jobs running for the same PR/issue
concurrency:
  group: claude-${{ github.event.pull_request.number || github.event.issue.number || 'manual' }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode for debugging'
        required: false
        type: boolean
        default: false
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]
    branches: [main, master]

jobs:
  # Interactive Claude mentions (simplified using centralized logic)
  claude-interactive:
    uses: dotCMS/claude-workflows/.github/workflows/claude-orchestrator.yml@v1.0.0
    with:
      trigger_mode: interactive
      allowed_tools: |
        Bash(git status)
        Bash(git diff)
      timeout_minutes: 15
      runner: ubuntu-latest
      enable_mention_detection: true  # Uses built-in @claude mention detection
      # custom_trigger_condition: |    # Optional: Override default mention detection
      #   your custom condition here
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  # Automatic PR reviews (no @claude mention required)
  claude-automatic-review:
    if: |
      github.event_name == 'pull_request' &&
      !contains(github.event.pull_request.title, '@claude') &&
      !contains(github.event.pull_request.title, '@Claude') &&
      !contains(github.event.pull_request.title, '@CLAUDE') &&
      !contains(github.event.pull_request.body, '@claude') &&
      !contains(github.event.pull_request.body, '@Claude') &&
      !contains(github.event.pull_request.body, '@CLAUDE')
    uses: dotCMS/claude-workflows/.github/workflows/claude-orchestrator.yml@v1.0.0
    with:
      trigger_mode: automatic
      direct_prompt: |
        Please review this pull request and provide feedback on:
        - Code quality and best practices
        - Potential bugs or issues
        - Performance considerations
        - Security concerns
        - Test coverage

        Be constructive and helpful in your feedback.
      allowed_tools: |
        Bash(git status)
        Bash(git diff)
      timeout_minutes: 15
      runner: ubuntu-latest
      enable_mention_detection: false  # No mention detection for automatic reviews
      # custom_trigger_condition: |     # Optional: Custom trigger logic
      #   your custom condition here
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}