---
# Remote AI Checks Workflow (Infrastructure-as-Code)
#
# PURPOSE: This workflow leverages the centralized Claude workflows from the
# claude-workflows repository to provide AI-powered code reviews and checks
# for infrastructure-as-code changes.
#
# WHY: Uses the DRY principle by leveraging the centralized workflow while
# maintaining infrastructure-specific configurations like path exclusions,
# allowed tools, and custom prompts for automatic reviews.
#
# USAGE: This calls the centralized claude-orchestrator which handles all
# trigger logic internally. We only define the webhook events here.

name: Remote AI Checks

# Concurrency control to prevent multiple jobs running for the same PR/issue
concurrency:
  group: claude-${{ github.event.pull_request.number || github.event.issue.number || 'manual' }}
  cancel-in-progress: false

# Define the webhook events here - the orchestrator will handle the conditional logic
on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode for debugging'
        required: false
        type: boolean
        default: false
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]
    # Ignore changes to customer-specific Kubernetes manifests and configs
    paths-ignore:
      - "kubernetes/customers/**/*.yml"
      - "kubernetes/customers/**/*.yaml"
      - "kubernetes/customers/**/*.json"     # Customer config files
      - "kubernetes/customers/**/*.md"       # Customer documentation

jobs:
  claude:
    uses: dotCMS/claude-workflows/.github/workflows/claude-orchestrator.yml@main
    with:
      # Infrastructure-specific automatic review prompt
      automatic_review_prompt: |
        Please review this pull request and provide feedback on:
        - Code quality and best practices
        - Potential bugs or issues
        - Performance considerations
        - Security concerns
        - Test coverage
        - Estimated cost spend or savings of the changes

        Be constructive and helpful in your feedback.
      # Infrastructure-specific allowed tools
      allowed_tools: |
        Bash(terraform validate)
        Bash(terraform plan)
        Bash(terraform fmt)
        Bash(terragrunt validate)
        Bash(terragrunt plan)
        Bash(terragrunt hclfmt)
        Bash(git status)
        Bash(git diff)
      timeout_minutes: 15
      runner: ubuntu-latest
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}