---
# Infrastructure-as-Code Consumer Workflow Example
# This example shows how to configure Claude workflows for infrastructure repositories
# with Terraform, Terragrunt, and Kubernetes-specific tooling.

name: Infrastructure AI Checks

# Concurrency control to prevent multiple jobs running for the same PR/issue
concurrency:
  group: claude-${{ github.event.pull_request.number || github.event.issue.number || 'manual' }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode for debugging'
        required: false
        type: boolean
        default: false
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]
    # Ignore changes to customer-specific configurations
    paths-ignore:
      - "kubernetes/customers/**/*.yml"
      - "kubernetes/customers/**/*.yaml"
      - "kubernetes/customers/**/*.json"
      - "kubernetes/customers/**/*.md"

jobs:
  # Interactive Claude mentions in comments
  claude-comment-mention:
    if: |
      (github.event_name == 'issue_comment' && (
        contains(github.event.comment.body, '@claude') ||
        contains(github.event.comment.body, '@Claude') ||
        contains(github.event.comment.body, '@CLAUDE')
      )) ||
      (github.event_name == 'pull_request_review_comment' && (
        contains(github.event.comment.body, '@claude') ||
        contains(github.event.comment.body, '@Claude') ||
        contains(github.event.comment.body, '@CLAUDE')
      ))
    uses: dotCMS/claude-workflows/.github/workflows/claude-simple.yml@main
    with:
      trigger_mode: interactive
      allowed_tools: |
        Bash(terraform validate)
        Bash(terraform plan)
        Bash(terraform fmt)
        Bash(terragrunt validate)
        Bash(terragrunt plan)
        Bash(terragrunt hclfmt)
        Bash(git status)
        Bash(git diff)
      timeout_minutes: 15
      runner: ubuntu-latest
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  # Interactive Claude mentions in PR reviews
  claude-review-mention:
    if: |
      github.event_name == 'pull_request_review' && (
        contains(github.event.review.body, '@claude') ||
        contains(github.event.review.body, '@Claude') ||
        contains(github.event.review.body, '@CLAUDE')
      )
    uses: dotCMS/claude-workflows/.github/workflows/claude-simple.yml@main
    with:
      trigger_mode: interactive
      allowed_tools: |
        Bash(terraform validate)
        Bash(terraform plan)
        Bash(terraform fmt)
        Bash(terragrunt validate)
        Bash(terragrunt plan)
        Bash(terragrunt hclfmt)
        Bash(git status)
        Bash(git diff)
      timeout_minutes: 15
      runner: ubuntu-latest
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  # Interactive Claude mentions in issues
  claude-issue-mention:
    if: |
      github.event_name == 'issues' &&
      (
        (
          contains(github.event.issue.body, '@claude') ||
          contains(github.event.issue.body, '@Claude') ||
          contains(github.event.issue.body, '@CLAUDE')
        ) ||
        (
          contains(github.event.issue.title, '@claude') ||
          contains(github.event.issue.title, '@Claude') ||
          contains(github.event.issue.title, '@CLAUDE')
        )
      )
    uses: dotCMS/claude-workflows/.github/workflows/claude-simple.yml@main
    with:
      trigger_mode: interactive
      allowed_tools: |
        Bash(terraform validate)
        Bash(terraform plan)
        Bash(terraform fmt)
        Bash(terragrunt validate)
        Bash(terragrunt plan)
        Bash(terragrunt hclfmt)
        Bash(git status)
        Bash(git diff)
      timeout_minutes: 15
      runner: ubuntu-latest
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  # Interactive Claude mentions in PR titles/bodies
  claude-pr-mention:
    if: |
      github.event_name == 'pull_request' &&
      (
        (
          contains(github.event.pull_request.title, '@claude') ||
          contains(github.event.pull_request.title, '@Claude') ||
          contains(github.event.pull_request.title, '@CLAUDE')
        ) ||
        (
          contains(github.event.pull_request.body, '@claude') ||
          contains(github.event.pull_request.body, '@Claude') ||
          contains(github.event.pull_request.body, '@CLAUDE')
        )
      )
    uses: dotCMS/claude-workflows/.github/workflows/claude-simple.yml@main
    with:
      trigger_mode: interactive
      allowed_tools: |
        Bash(terraform validate)
        Bash(terraform plan)
        Bash(terraform fmt)
        Bash(terragrunt validate)
        Bash(terragrunt plan)
        Bash(terragrunt hclfmt)
        Bash(git status)
        Bash(git diff)
      timeout_minutes: 15
      runner: ubuntu-latest
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  # Automatic PR reviews (no @claude mention)
  claude-automatic-review:
    if: |
      github.event_name == 'pull_request' &&
      !contains(github.event.pull_request.title, '@claude') &&
      !contains(github.event.pull_request.title, '@Claude') &&
      !contains(github.event.pull_request.title, '@CLAUDE') &&
      !contains(github.event.pull_request.body, '@claude') &&
      !contains(github.event.pull_request.body, '@Claude') &&
      !contains(github.event.pull_request.body, '@CLAUDE')
    uses: dotCMS/claude-workflows/.github/workflows/claude-simple.yml@main
    with:
      trigger_mode: automatic
      direct_prompt: |
        Please review this infrastructure-as-code pull request and provide feedback on:
        - Code quality and best practices
        - Potential bugs or issues
        - Performance considerations
        - Security concerns
        - Test coverage
        - Estimated cost spend or savings of the changes
        - Terraform/Terragrunt best practices
        - Resource naming conventions
        - Infrastructure security implications

        Be constructive and helpful in your feedback.
      allowed_tools: |
        Bash(terraform validate)
        Bash(terraform plan)
        Bash(terraform fmt)
        Bash(terragrunt validate)
        Bash(terragrunt plan)
        Bash(terragrunt hclfmt)
        Bash(git status)
        Bash(git diff)
      timeout_minutes: 15
      runner: ubuntu-latest
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}